// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/putko-variations/PutkoOrbit.tsx": () => import("../components/mockups/putko-variations/PutkoOrbit.tsx"),
  "./components/mockups/templates/ArtisanalCoffeeLandingPage-PfSAD9/Lp04.tsx": () => import("../components/mockups/templates/ArtisanalCoffeeLandingPage-PfSAD9/Lp04.tsx")
};
